const source = {
    "data":[
        {"id":341628757,"title":"Быстрая зарядка для iphone комплект кабель Type-C Lighting Блок питания 20W 11 / 12 pro max / 13 fast charger","title_suffix":null,"price":694,"old_price":1083,"price_pcs":"23.73","href":"https://rozetka.com.ua/341628757/p341628757/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"Без бренда","brand_id":581286,"group_id":45354379,"group_name":"bystraya-zaryadka-dlya-iphone-komplekt-kabel-typ-c-lighting-blok-pitanie-20w-11-12-pro-max-13","group_title":"Быстрая зарядка для iphone комплект кабель Typ-C Lighting Блок питание 20W 11/12 pro max /13","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":6,"comments_mark":3.2,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content.rozetka.com.ua/goods/images/big_tile/272004130.jpg","images":{"main":"https://content.rozetka.com.ua/goods/images/big_tile/272004130.jpg","preview":"https://content.rozetka.com.ua/goods/images/preview/272004130.jpg","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/272004145.jpg","all_images":["https://content.rozetka.com.ua/goods/images/original/272004130.jpg","https://content1.rozetka.com.ua/goods/images/original/272004145.jpg","https://content1.rozetka.com.ua/goods/images/original/272004155.jpg","https://content1.rozetka.com.ua/goods/images/original/272004166.jpg","https://content2.rozetka.com.ua/goods/images/original/272004175.jpg","https://content.rozetka.com.ua/goods/images/original/272004184.jpg","https://content1.rozetka.com.ua/goods/images/original/272004197.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"64%","discount":36,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":296578448,"title":"Быстрая зарядка для iphone 11/12 комплект кабель Typ-C Lighting Блок питание 20W PAVLYSH (PZ-24)","title_suffix":"","price":695,"old_price":1008,"price_pcs":"23.76","href":"https://rozetka.com.ua/296578448/p296578448/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"PAVLYSH","brand_id":613893,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":9,"comments_mark":3.3,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/272237846.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/272237846.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/272237846.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/272237848.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/272237846.jpg","https://content2.rozetka.com.ua/goods/images/original/272237848.jpg","https://content.rozetka.com.ua/goods/images/original/272237850.jpg","https://content.rozetka.com.ua/goods/images/original/272237856.jpg","https://content1.rozetka.com.ua/goods/images/original/272237862.jpg","https://content.rozetka.com.ua/goods/images/original/272237866.jpg","https://content2.rozetka.com.ua/goods/images/original/272237871.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"66%","discount":31,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":288956798,"title":"Комплект быстрой зарядки для Apple iPhone, Сетевое зарядное устройство 18W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","title_suffix":null,"price":798,"old_price":899,"price_pcs":"27.28","href":"https://rozetka.com.ua/288956798/p288956798/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":90168,"merchant_id":17,"brand":null,"brand_id":null,"group_id":45070810,"group_name":"komplekt-bystroy-zaryadki-hifriend-dlya-apple-iphone-18w-usb-c-power-adapter-type-c-kabel-zaryadki-usb-c-to-lightning","group_title":"Комплект быстрой зарядки Hifriend для Apple iPhone 18W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":45,"comments_mark":4.9,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/259585966.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/259585966.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/259585966.jpg","hover":"https://content.rozetka.com.ua/goods/images/big_tile/259585973.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/259585966.jpg","https://content.rozetka.com.ua/goods/images/original/259585973.jpg","https://content2.rozetka.com.ua/goods/images/original/259585980.jpg","https://content2.rozetka.com.ua/goods/images/original/259585983.jpg","https://content1.rozetka.com.ua/goods/images/original/259585985.jpg","https://content2.rozetka.com.ua/goods/images/original/259585987.jpg","https://content2.rozetka.com.ua/goods/images/original/259585989.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"98%","discount":11,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":307411063,"title":"Беспроводная зарядка для apple iPhone 12 MagSafe Charger Foxconn White (A03896) + Подарок Кабель для Apple Lightning","title_suffix":"","price":970,"old_price":1940,"price_pcs":"33.16","href":"https://rozetka.com.ua/307411063/p307411063/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":28440,"merchant_id":17,"brand":"Foxconn","brand_id":350,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":16,"comments_mark":4.9,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/270443772.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/270443772.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/270443772.jpg","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/270443785.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/270443772.jpg","https://content1.rozetka.com.ua/goods/images/original/270443785.jpg","https://content1.rozetka.com.ua/goods/images/original/270443798.jpg","https://content.rozetka.com.ua/goods/images/original/270443811.jpg","https://content2.rozetka.com.ua/goods/images/original/270443827.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"98%","discount":50,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":340278623,"title":"Зарядная станция 32А 22кВт Тype 2 кабель 5 м Wi-Fi Bluetooth 230/400В Wallbox Commander 2 (CMX2-0-2-4-8-002)","title_suffix":null,"price":48979,"old_price":57627,"price_pcs":"1674.5","href":"https://rozetka.com.ua/340278623/p340278623/","status":"active","status_inherited":"active","sell_status":"available","category_id":4647502,"seller_id":149104,"merchant_id":17,"brand":"Wallbox","brand_id":652037,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627893.81203.4625901.4647502.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/271260522.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/271260522.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/271260522.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/271260555.png","all_images":["https://content2.rozetka.com.ua/goods/images/original/271260522.jpg","https://content2.rozetka.com.ua/goods/images/original/271260555.png","https://content.rozetka.com.ua/goods/images/original/271260563.jpg","https://content2.rozetka.com.ua/goods/images/original/271260568.png","https://content1.rozetka.com.ua/goods/images/original/271260585.png","https://content1.rozetka.com.ua/goods/images/original/271260594.jpg","https://content1.rozetka.com.ua/goods/images/original/271260599.jpg","https://content2.rozetka.com.ua/goods/images/original/271260604.jpg","https://content1.rozetka.com.ua/goods/images/original/271260611.png","https://content1.rozetka.com.ua/goods/images/original/271260615.jpg","https://content.rozetka.com.ua/goods/images/original/271260618.jpg","https://content1.rozetka.com.ua/goods/images/original/271260619.jpg"]},"parent_category_id":4627893,"primary_good_title":null,"groups":[],"stars":"0%","discount":15,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":338347336,"title":"Сетевое зарядное устройство BASEUS Type-C to Type-C cable Super Si Quick Charger 1Type-C, 3A/25W адаптер с кабелем Type-C 1м и быстрой зарядкой Black (TZCCSUP-L01)","title_suffix":null,"price":649,"old_price":0,"price_pcs":"22.19","href":"https://rozetka.com.ua/338347336/p338347336/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":41652,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":1,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/260087813.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/260087813.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/260087813.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/260087822.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/260087813.jpg","https://content2.rozetka.com.ua/goods/images/original/260087822.jpg","https://content2.rozetka.com.ua/goods/images/original/260087835.jpg","https://content1.rozetka.com.ua/goods/images/original/260087845.jpg","https://content.rozetka.com.ua/goods/images/original/260087856.jpg","https://content1.rozetka.com.ua/goods/images/original/260087863.jpg","https://content1.rozetka.com.ua/goods/images/original/260087872.jpg","https://content1.rozetka.com.ua/goods/images/original/260087883.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":0,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":332349124,"title":"Сетевое зарядное устройство USB-C блок питания 20W Power Adapter для Apple iPhone/iPad + Кабель зарядки USB-C to Lightning","title_suffix":null,"price":777,"old_price":1000,"price_pcs":"26.56","href":"https://rozetka.com.ua/332349124/p332349124/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":125458,"merchant_id":17,"brand":null,"brand_id":null,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/270446402.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/270446402.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/270446402.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/270446416.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/270446402.jpg","https://content2.rozetka.com.ua/goods/images/original/270446416.jpg","https://content1.rozetka.com.ua/goods/images/original/270446424.jpg","https://content.rozetka.com.ua/goods/images/original/270446432.jpg","https://content.rozetka.com.ua/goods/images/original/270446440.jpg","https://content2.rozetka.com.ua/goods/images/original/270446447.jpg","https://content1.rozetka.com.ua/goods/images/original/270446454.jpg","https://content1.rozetka.com.ua/goods/images/original/270446459.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":22,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":271165271,"title":"Сетевое зарядное устройство Foxconn для Iphone 11/12 Pro Max 20W + Кабель USB-C to Lightining 1 м White","title_suffix":"","price":848,"old_price":1099,"price_pcs":"28.99","href":"https://rozetka.com.ua/271165271/p271165271/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":94447,"merchant_id":17,"brand":"Foxconn","brand_id":350,"group_id":40283958,"group_name":"zaradnoe-ustrojstvo-foxconn-dla-iphone-1112-pro-max-20w-kabel-usb-c-to-lightining-1-m-white","group_title":"Зарядное устройство Foxconn 20W USB-C Power Adapter + кабель зарядки USB-C to Lightning","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":2,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/177865846.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/177865846.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/177865846.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/177865847.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/177865846.jpg","https://content2.rozetka.com.ua/goods/images/original/177865847.jpg","https://content1.rozetka.com.ua/goods/images/original/177865848.jpg","https://content1.rozetka.com.ua/goods/images/original/177865849.jpg","https://content.rozetka.com.ua/goods/images/original/177865851.jpg","https://content1.rozetka.com.ua/goods/images/original/177865854.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":23,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":288956793,"title":"Комплект быстрой зарядки для Apple iPhone, Сетевое зарядное устройство 20W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","title_suffix":null,"price":799,"old_price":999,"price_pcs":"27.32","href":"https://rozetka.com.ua/288956793/p288956793/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":90168,"merchant_id":17,"brand":null,"brand_id":null,"group_id":45070795,"group_name":"komplekt-bystroy-zaryadki-hifriend-dlya-apple-iphone-20w-usb-c-power-adapter-type-c-kabel-zaryadki-usb-c-to-lightning","group_title":"Комплект быстрой зарядки Hifriend для Apple iPhone 20W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":21,"comments_mark":4.7,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/258693236.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/258693236.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/258693236.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/258693241.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/258693236.jpg","https://content2.rozetka.com.ua/goods/images/original/258693241.jpg","https://content.rozetka.com.ua/goods/images/original/258693243.jpg","https://content.rozetka.com.ua/goods/images/original/258693246.jpg","https://content2.rozetka.com.ua/goods/images/original/258693248.jpg","https://content2.rozetka.com.ua/goods/images/original/258693252.jpg","https://content2.rozetka.com.ua/goods/images/original/258693254.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"94%","discount":20,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":310924068,"title":"Комплект зарядки для Apple iPhone, Сетевое зарядное устройство 5W USB Power Adapter , Кабель зарядки USB to Lightning","title_suffix":null,"price":249,"old_price":399,"price_pcs":"8.51","href":"https://rozetka.com.ua/310924068/p310924068/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":90168,"merchant_id":17,"brand":null,"brand_id":null,"group_id":45070834,"group_name":"zaryadnoe-ustroystvo-hifriend-dlya-apple-usb-power-adapter-5w-plus-kabel-usb-to-lightning-1m","group_title":"Зарядное устройство Hifriend для Apple USB Power Adapter 5W + Кабель USB to Lightning 1м","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":15,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/195257199.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/195257199.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/195257199.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/195257212.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/195257199.jpg","https://content2.rozetka.com.ua/goods/images/original/195257212.jpg","https://content2.rozetka.com.ua/goods/images/original/195257223.jpg","https://content2.rozetka.com.ua/goods/images/original/195257231.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":38,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":252881881,"title":"Кабель для iPhone Lightning to USB кабель зарядки для iPad IOS 1m и блок питания зарядный Комплект White PAVLYSH (PZ-05)","title_suffix":"","price":369,"old_price":535,"price_pcs":"12.62","href":"https://rozetka.com.ua/252881881/p252881881/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"PAVLYSH","brand_id":613893,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":33,"comments_mark":3.1,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/270483273.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/270483273.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/270483273.jpg","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/270483281.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/270483273.jpg","https://content1.rozetka.com.ua/goods/images/original/270483281.jpg","https://content2.rozetka.com.ua/goods/images/original/270483287.jpg","https://content2.rozetka.com.ua/goods/images/original/270483298.jpg","https://content.rozetka.com.ua/goods/images/original/270483310.jpg","https://content2.rozetka.com.ua/goods/images/original/270483318.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"62%","discount":31,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":338704654,"title":"Сетевое зарядное устройство BASEUS Type-C to Type-C Cable GaN2 Fast Charger 1C |1Type-C, QC/PD, 100W, 5A| с кабелем Type-C 1.5м. и быстрой зарядкой Black (TZCCGAN-L01)","title_suffix":null,"price":2049,"old_price":0,"price_pcs":"70.05","href":"https://rozetka.com.ua/338704654/p338704654/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":41652,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/260746437.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/260746437.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/260746437.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/260746442.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/260746437.jpg","https://content2.rozetka.com.ua/goods/images/original/260746442.jpg","https://content1.rozetka.com.ua/goods/images/original/260746447.jpg","https://content2.rozetka.com.ua/goods/images/original/260746455.jpg","https://content.rozetka.com.ua/goods/images/original/260746474.jpg","https://content.rozetka.com.ua/goods/images/original/260746478.jpg","https://content.rozetka.com.ua/goods/images/original/260746484.jpg","https://content1.rozetka.com.ua/goods/images/original/260746507.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":0,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":341707378,"title":"Зарядное устройство для iPhone 11/12 Pro Max 18W с Кабелем USB-C to Lightining Foxconn 1м Белый","title_suffix":null,"price":594,"old_price":861,"price_pcs":"20.31","href":"https://rozetka.com.ua/341707378/p341707378/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"Без бренда","brand_id":581286,"group_id":40283968,"group_name":"zaradnoe-ustrojstvo-foxconn-dla-iphone-1112-pro-max-18w-i-kabel-usb-c-to-lightining-1-m-white","group_title":"Зарядное устройство Foxconn для Iphone 11/12 Pro Max 18W и Кабель USB-C to Lightining 1 м White","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":2,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/272004177.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/272004177.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/272004177.jpg","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/272004189.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/272004177.jpg","https://content1.rozetka.com.ua/goods/images/original/272004189.jpg","https://content1.rozetka.com.ua/goods/images/original/272004200.jpg","https://content1.rozetka.com.ua/goods/images/original/272004209.jpg","https://content.rozetka.com.ua/goods/images/original/272004218.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":31,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":342500296,"title":"Зарядное устройство для телефона USB 2.1А блок питания зарядка для смартфона + кабель 1м Type-C Kingyou KC88E White","title_suffix":null,"price":289,"old_price":400,"price_pcs":"9.88","href":"https://rozetka.com.ua/342500296/p342500296/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":100981,"merchant_id":17,"brand":"KingYou","brand_id":495804,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content.rozetka.com.ua/goods/images/big_tile/267656521.jpg","images":{"main":"https://content.rozetka.com.ua/goods/images/big_tile/267656521.jpg","preview":"https://content.rozetka.com.ua/goods/images/preview/267656521.jpg","hover":"https://content.rozetka.com.ua/goods/images/big_tile/267656529.jpg","all_images":["https://content.rozetka.com.ua/goods/images/original/267656521.jpg","https://content.rozetka.com.ua/goods/images/original/267656529.jpg","https://content.rozetka.com.ua/goods/images/original/267656536.jpg","https://content.rozetka.com.ua/goods/images/original/267656543.jpg","https://content2.rozetka.com.ua/goods/images/original/267656550.jpg","https://content1.rozetka.com.ua/goods/images/original/267656558.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":28,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":289791458,"title":"Зарядное устройство Baseus GaN 2 PRO Quick Charger 65W (2 Type-С+USB) + кабель USB-C 100W для MacBook/iPad/iPhone/Android white","title_suffix":"","price":1990,"old_price":2200,"price_pcs":"68.03","href":"https://rozetka.com.ua/289791458/p289791458/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":67449,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":35942563,"group_name":"35942563","group_title":"Зарядное устройство Baseus GaN Quick Charger 65W (2 Type-С+USB) для MacBook/iPad/iPhone/Android","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":9,"comments_mark":3.3,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/183796789.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/183796789.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/183796789.jpg","hover":"https://content.rozetka.com.ua/goods/images/big_tile/183796793.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/183796789.jpg","https://content.rozetka.com.ua/goods/images/original/183796793.jpg","https://content1.rozetka.com.ua/goods/images/original/183796812.jpg","https://content2.rozetka.com.ua/goods/images/original/183796825.jpg","https://content1.rozetka.com.ua/goods/images/original/183796837.jpg","https://content1.rozetka.com.ua/goods/images/original/183796843.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"66%","discount":10,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":286783233,"title":"Зарядное устройство Baseus GaN 120W Quick Charger 4.0/PD 3.0 + кабель USB-C 100W для MacBook/iPad/iPhone/Android black","title_suffix":"","price":3280,"old_price":3400,"price_pcs":"112.14","href":"https://rozetka.com.ua/286783233/p286783233/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":67449,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":40280633,"group_name":"zaradnoe-ustrojstvo-baseus-gan-120w-quick-charger-40pd-30-kabel-usb-c-100w","group_title":"Зарядное устройство Baseus GaN 120W Quick Charger 4.0/PD 3.0 + кабель USB-C 100W","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":1,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/185244411.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/185244411.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/185244411.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/185244422.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/185244411.jpg","https://content2.rozetka.com.ua/goods/images/original/185244422.jpg","https://content2.rozetka.com.ua/goods/images/original/185244437.jpg","https://content.rozetka.com.ua/goods/images/original/185244448.jpg","https://content2.rozetka.com.ua/goods/images/original/185244460.jpg","https://content1.rozetka.com.ua/goods/images/original/185244477.jpg","https://content2.rozetka.com.ua/goods/images/original/185244489.jpg","https://content.rozetka.com.ua/goods/images/original/185244497.jpg","https://content2.rozetka.com.ua/goods/images/original/185244505.jpg","https://content2.rozetka.com.ua/goods/images/original/185244508.jpg","https://content1.rozetka.com.ua/goods/images/original/185244512.jpg","https://content1.rozetka.com.ua/goods/images/original/185244517.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":4,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":321423016,"title":"Автомобильное зарядное устройство Baseus Superme Digital Display 100W High Power QC4.0+PD3.0 PPS (USB + Type-C) с кабелем Type-C to Type-C 100W (20V/5A), 1 м (TZCCZX-01)","title_suffix":null,"price":1198,"old_price":1500,"price_pcs":"40.96","href":"https://rozetka.com.ua/321423016/p321423016/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":42778,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":1,"comments_mark":4,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/226816375.png","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/226816375.png","preview":"https://content1.rozetka.com.ua/goods/images/preview/226816375.png","hover":"https://content.rozetka.com.ua/goods/images/big_tile/226816385.png","all_images":["https://content1.rozetka.com.ua/goods/images/original/226816375.png","https://content.rozetka.com.ua/goods/images/original/226816385.png","https://content2.rozetka.com.ua/goods/images/original/226816390.png","https://content.rozetka.com.ua/goods/images/original/226816396.png","https://content.rozetka.com.ua/goods/images/original/226816400.png","https://content.rozetka.com.ua/goods/images/original/226816403.png","https://content1.rozetka.com.ua/goods/images/original/226816406.png","https://content1.rozetka.com.ua/goods/images/original/226816408.png","https://content1.rozetka.com.ua/goods/images/original/226816409.png"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"80%","discount":20,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":312735163,"title":"Зарядное устройство Baseus GaN2 100W Quick Charge 5.0 |1xType-C, QC/PD, 5A| + кабель USB-C 100W для iPad/iPhone/Huawei/Samsung/Asus/Google/Lenovo black","title_suffix":null,"price":2490,"old_price":2800,"price_pcs":"85.13","href":"https://rozetka.com.ua/312735163/p312735163/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":67449,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/198220182.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/198220182.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/198220182.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/198220189.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/198220182.jpg","https://content2.rozetka.com.ua/goods/images/original/198220189.jpg","https://content1.rozetka.com.ua/goods/images/original/198220195.jpg","https://content2.rozetka.com.ua/goods/images/original/198220205.jpg","https://content2.rozetka.com.ua/goods/images/original/198220216.jpg","https://content2.rozetka.com.ua/goods/images/original/198220226.jpg","https://content2.rozetka.com.ua/goods/images/original/198220236.jpg","https://content.rozetka.com.ua/goods/images/original/198220244.jpg","https://content2.rozetka.com.ua/goods/images/original/198220251.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":11,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":303236703,"title":"Кабель для iPhone Lightning to USB кабель зарядки для iPad IOS 2m и блок питания зарядный Комплект White PAVLYSH (PZ-20)","title_suffix":"","price":226,"old_price":328,"price_pcs":"7.73","href":"https://rozetka.com.ua/303236703/p303236703/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"PAVLYSH","brand_id":613893,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":6,"comments_mark":2.8,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content.rozetka.com.ua/goods/images/big_tile/271435893.jpg","images":{"main":"https://content.rozetka.com.ua/goods/images/big_tile/271435893.jpg","preview":"https://content.rozetka.com.ua/goods/images/preview/271435893.jpg","hover":"https://content.rozetka.com.ua/goods/images/big_tile/271435899.jpg","all_images":["https://content.rozetka.com.ua/goods/images/original/271435893.jpg","https://content.rozetka.com.ua/goods/images/original/271435899.jpg","https://content2.rozetka.com.ua/goods/images/original/271435905.jpg","https://content1.rozetka.com.ua/goods/images/original/271435910.jpg","https://content2.rozetka.com.ua/goods/images/original/271435914.jpg","https://content2.rozetka.com.ua/goods/images/original/271435915.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"56%","discount":31,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":337369201,"title":"Комплект быстрой зарядки 20 Вт для Apple iPhone iPod, Сетевое зарядное устройство 20W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","title_suffix":null,"price":749,"old_price":899,"price_pcs":"25.61","href":"https://rozetka.com.ua/337369201/p337369201/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":90168,"merchant_id":17,"brand":null,"brand_id":null,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":3,"comments_mark":5,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content2.rozetka.com.ua/goods/images/big_tile/258089709.jpg","images":{"main":"https://content2.rozetka.com.ua/goods/images/big_tile/258089709.jpg","preview":"https://content2.rozetka.com.ua/goods/images/preview/258089709.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/258089719.jpg","all_images":["https://content2.rozetka.com.ua/goods/images/original/258089709.jpg","https://content2.rozetka.com.ua/goods/images/original/258089719.jpg","https://content2.rozetka.com.ua/goods/images/original/258089730.jpg","https://content2.rozetka.com.ua/goods/images/original/258089738.jpg","https://content.rozetka.com.ua/goods/images/original/258089748.jpg","https://content.rozetka.com.ua/goods/images/original/258089753.jpg","https://content2.rozetka.com.ua/goods/images/original/258089760.jpg","https://content1.rozetka.com.ua/goods/images/original/258089768.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"100%","discount":17,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":337369213,"title":"Комплект быстрой зарядки для Apple iPhone iPod, Сетевое зарядное устройство 18W USB-C Power Adapter (Type-C), Кабель зарядки USB-C to Lightning","title_suffix":null,"price":719,"old_price":799,"price_pcs":"24.58","href":"https://rozetka.com.ua/337369213/p337369213/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":90168,"merchant_id":17,"brand":null,"brand_id":null,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content.rozetka.com.ua/goods/images/big_tile/258089724.jpg","images":{"main":"https://content.rozetka.com.ua/goods/images/big_tile/258089724.jpg","preview":"https://content.rozetka.com.ua/goods/images/preview/258089724.jpg","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/258089734.jpg","all_images":["https://content.rozetka.com.ua/goods/images/original/258089724.jpg","https://content1.rozetka.com.ua/goods/images/original/258089734.jpg","https://content.rozetka.com.ua/goods/images/original/258089742.jpg","https://content.rozetka.com.ua/goods/images/original/258089751.jpg","https://content.rozetka.com.ua/goods/images/original/258089763.jpg","https://content.rozetka.com.ua/goods/images/original/258089770.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":10,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":342227389,"title":"Кабель Baseus Yiven USB - Lightning для Apple iPhone / iPad / iPod Lightning 2.0 A (1.8 м) Black","title_suffix":null,"price":235,"old_price":0,"price_pcs":"8.03","href":"https://rozetka.com.ua/342227389/p342227389/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":55821,"merchant_id":17,"brand":"Baseus","brand_id":144596,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/267077337.jpg","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/267077337.jpg","preview":"https://content1.rozetka.com.ua/goods/images/preview/267077337.jpg","hover":"https://content.rozetka.com.ua/goods/images/big_tile/267077345.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/267077337.jpg","https://content.rozetka.com.ua/goods/images/original/267077345.jpg","https://content2.rozetka.com.ua/goods/images/original/267077351.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":0,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":339148498,"title":"Кабель для iPhone Lightning to USB 1M Кабель зарядки для iPad IOS + блок питания, зарядный комплект для Apple PAVLYSH 72","title_suffix":null,"price":293,"old_price":440,"price_pcs":"10.02","href":"https://rozetka.com.ua/339148498/p339148498/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":47788,"merchant_id":17,"brand":"DXtech","brand_id":402294,"group_id":45070819,"group_name":"zaryadnoe-ustroystvo-dxtech-dlya-iphone-apple-lightning-to-usb-kabel-zaryadki-dlya-ipad-ios-1m","group_title":"Зарядное устройство DXtech для iPhone Apple Lightning to USB кабель зарядки для iPad IOS 1m","pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":1,"dispatch":0,"premium":0,"preorder":0,"comments_amount":12,"comments_mark":4.3,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content.rozetka.com.ua/goods/images/big_tile/271437004.jpg","images":{"main":"https://content.rozetka.com.ua/goods/images/big_tile/271437004.jpg","preview":"https://content.rozetka.com.ua/goods/images/preview/271437004.jpg","hover":"https://content2.rozetka.com.ua/goods/images/big_tile/271437016.jpg","all_images":["https://content.rozetka.com.ua/goods/images/original/271437004.jpg","https://content2.rozetka.com.ua/goods/images/original/271437016.jpg","https://content2.rozetka.com.ua/goods/images/original/271437026.jpg","https://content2.rozetka.com.ua/goods/images/original/271437034.jpg","https://content.rozetka.com.ua/goods/images/original/271437045.jpg","https://content.rozetka.com.ua/goods/images/original/271437056.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"86%","discount":33,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}},
        {"id":338080090,"title":"Сетевое зарядное устройство HOCO N6 |2USB, 3A, 2xQC3.0, 18W| адаптер с micro-USB кабелем 1м и быстрой зарядкой Black (N6MUB)","title_suffix":null,"price":359,"old_price":0,"price_pcs":"12.27","href":"https://rozetka.com.ua/338080090/p338080090/","status":"active","status_inherited":"active","sell_status":"available","category_id":146341,"seller_id":41652,"merchant_id":17,"brand":"Hoco","brand_id":2930,"group_id":0,"group_name":null,"group_title":null,"pl_bonus_charge_pcs":0,"pl_use_instant_bonus":0,"state":"new","docket":"","mpath":".4627949.80263.146341.","is_group_primary":0,"dispatch":0,"premium":0,"preorder":0,"comments_amount":0,"comments_mark":0,"gift":null,"tag":null,"pictograms":null,"title_mode":null,"use_group_links":null,"is_need_street_id":false,"image_main":"https://content1.rozetka.com.ua/goods/images/big_tile/259642437.png","images":{"main":"https://content1.rozetka.com.ua/goods/images/big_tile/259642437.png","preview":"https://content1.rozetka.com.ua/goods/images/preview/259642437.png","hover":"https://content1.rozetka.com.ua/goods/images/big_tile/259642449.jpg","all_images":["https://content1.rozetka.com.ua/goods/images/original/259642437.png","https://content1.rozetka.com.ua/goods/images/original/259642449.jpg","https://content1.rozetka.com.ua/goods/images/original/259642460.jpg","https://content.rozetka.com.ua/goods/images/original/259642467.jpg","https://content2.rozetka.com.ua/goods/images/original/259642476.png","https://content2.rozetka.com.ua/goods/images/original/259642482.jpg","https://content1.rozetka.com.ua/goods/images/original/259642485.jpg","https://content.rozetka.com.ua/goods/images/original/259642488.jpg"]},"parent_category_id":4627949,"primary_good_title":null,"groups":[],"stars":"0%","discount":0,"config":{"title":true,"brand":false,"image":true,"price":true,"old_price":true,"promo_price":true,"status":true,"bonus":true,"gift":true,"rating":true,"wishlist_button":true,"compare_button":true,"buy_button":true,"tags":true,"pictograms":true,"description":true,"variables":true}}
    ]};

    export interface IProductCardListItem {
        imageCollection: string[];
        available: boolean;
        novelty: boolean;
        model: string;
        name: string;
        specifications: {
          main: {
            icon: string | JSX.Element;
            description: string;
            value: string;
          }[];
          detailed: {
            title: string;
            value: string[];
          }[];
          article: {
            title: string;
            content: string;
            subcontent: string;
            photo: string[];
          }[];
          colors: {
            color: string;
            colorName: string;
          }[];
          ram: number[];
          memorySize: string[];
          corps: string[];
        };
        category: {
          mainImage: string;
          coupled: number[];
          name: string;
          top: boolean;
          id: number;
        };
        oldprice: number;
        leader: boolean;
        price: number;
        id: number;
        brand: {
          country: string;
          name: string;
          logo: string;
          id: number;
        };
      }
    export const getData: () => IProductCardListItem[] = () => {
        let data: IProductCardListItem[] = [];

        let source1 = source.data;
        source1.forEach((item, index) => {
            let good: IProductCardListItem = {
                imageCollection: [],
                available: true,
                novelty: false,
                model: '',
                name: '',
                specifications: {
                    main: [],
                    detailed: [],
                    article: [],
                    colors: [],
                    ram: [],
                    memorySize: [],
                    corps: [],
                },
                category: {
                    mainImage: '',
                    coupled: [],
                    name: '',
                    top: false,
                    id: 0,
                },
                oldprice: 0,
                leader: false,
                price: 0,
                id: 0,
                brand: {
                    country: '',
                    name: '',
                    logo: '',
                    id: 0,
                },
            };
            // images
            if (item.images.all_images) {
                good.imageCollection = item.images.all_images;
            }
            // available
            if (index % 3 === 0) {
                good.available = false;
            }
            else {
                good.available = true;
            }
            // novelty
            if (index % 4 === 0) {
                good.novelty = true;
            }
            else {
                good.novelty = false;
            }

            // model
            good.model = `Model ${index}`;
            // title
            if (item.title) {
                good.name = item.title;
            }
            // specifications
            good.specifications.main.push({icon: '', description: 'Совместимость', value: 'Универсальный'});
            good.specifications.main.push({icon: '', description: 'Количество USB-портов', value: '1'});
            good.specifications.main.push({icon: '', description: 'Быстрая зарядка', value: 'Quick Charge 3.0'});
            // detailed
            good.specifications.detailed.push({title: '', value: ['Идеальное решение для быстрой и эффективной зарядки твоих устройств в машине. А встроенный спиральный кабель оптимизирует пространство в авто и избавит от необходимости покупки дополнительного провода.']});
            // article
            good.specifications.article.push({title: '', content: 'USB-C Power Delivery коннектор: Молниеносная скорость зарядки смартфона, планшета или повербанка на мощности до 33 Вт.', subcontent: '', photo: ['']});
            // color
            good.specifications.colors.push({color: "#fff", colorName: 'Білий'});
            // ram
            //good.specifications.ram.push(0);
            // memory size
            //good.specifications.memorySize.push('');
            // category
            good.category.name = "Зарядні пристрої та кабелі";
            good.category.id = 1;
            if (index % 4 === 0) {
                good.category.top = true;
            }
            else {
                good.category.top = false;
            }
            // oldprice
            if (item.old_price) {
                good.oldprice = item.old_price;
            }
            // leader
            if (index % 6 === 6) {
                good.leader = true;
            }
            else {
                good.leader = false;
            }
            // price
            if (item.price) {
                good.price = item.price;
            }
            // id
            if (item.id) {
                good.id = item.id;
            }
            // brand
            good.brand.id = 1;
            data.push(good);
        });
        return data;
    }
    export {source};